### ISSUE TITLE
testEnableBluetooth fails on Samsung Galaxy S6 (SM-G920F - Android 7.0)

### ISSUE THREAD

**Issue by calfr** [nhsx/COVID-19-app-Android-BETA#12]
While trying to run the tests on my device, I recieve an `java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference` during the testEnableBluetooth test.

From reading through the test and the traceback, I believe it is due to the test looking for a button text of "Allow" or "ALLOW" in order to allow permissions; however my device appears to show a prompt of YES and NO (for Allow and Deny respectively). 
This presumably could also apply to other devices with other prompt designs for permissions.

**Comment by edent** [comment]
Thanks - we'll take a look into it.
