### ISSUE TITLE
Tests do not appear to support Android API Version < 26

### ISSUE THREAD

**Issue by calfr** [nhsx/COVID-19-app-Android-BETA#13]
AssertJ Core 3.x, which is used within some of the tests, [only supports Android API Level 26+](https://assertj.github.io/doc/#assertj-core-android), but the Application is stated to support a minimum SDK version of 24, which evidently is less than 26.

As a result, attempting to run the test suite will eventually result in the exception `java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: ...
` being raised - with java.time.Duration having only been introduced at API Level 26.

Is there a workaround available for this? An older version of AssertJ exists that supports older Android API levels, however this causes an error within the TestRxBleClient class when attempting to change the build to use that version.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
