### ISSUE TITLE
gradle minSdkVersion doesn't match what it says on app's website

### ISSUE THREAD

**Issue by zikalify** [nhsx/COVID-19-app-Android-BETA#19]
According to the [app's website](https://covid19.nhs.uk/using-the-app.html), it says you need Android 8+ for the app to work but the minSdkVersion in the [build.gradle](https://github.com/nhsx/COVID-19-app-Android-BETA/blob/master/app/build.gradle) file is set to 24 (Android 7) instead of 26 (Android 8).

**Comment by calfr** [comment]
This would somewhat explain #12 and #13 if Version 8.0 is intended to be the lowest working API version - although the Google Play Store also seems happy to install the application on my device.
Could it be a case of "possible but not supported" or are one of the two sources outdated?

**Comment by steffandroid** [comment]
My guess would be that it was initially built with a minSdk of 26 and was since lowered, but the tests weren't updated to be compatible.

From what I can see, it would be fairly trivial to lower the minSdk to 23, which would be great for increasing coverage.

**Comment by edent** [comment]
Oh, good catch. I'll take it up with the team and get that corrected.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
