### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by gilescope** [nhsx/COVID-19-app-Android-BETA#20]
Can there be a Glitter / Matrix chat room so that contributers can help bootstrap other contributers to get started and answer questions without the core maintainers needing to get involved? (We don't want to take up any of their precious time!) 

(Pinging @lampholder )

**Comment by lampholder** [comment]
Hiya - if you'd like to use a Matrix room I've set up a couple (one for Android, one for iOS):

https://riot.im/app/#/room/#nhsx-covid-android:matrix.org
https://riot.im/app/#/room/#nhsx-covid-ios:matrix.org

matrix.to links if you don't want to jump straight into the Riot app:
- [Android](https://matrix.to/#/!DUestmBrLYsBaSiGdc:matrix.org?via=matrix.org)
- [iOS](https://matrix.to/#/!SaXQZLJDFTmEcgQUgU:matrix.org?via=matrix.org)

**Comment by lampholder** [comment]
I've set up with a basic room name/alias/avatar etc. - if people want to volunteer as moderators let me know 😄

**Comment by gilescope** [comment]
Thanks @lampholder (he also said he could bridge it to a gitter room if one shows up)

**Comment by edent** [comment]
Hi, as these aren't official chat rooms, we won't be able to promote them in the README etc. I'd ask that if you do run an unofficial chat room, please make sure it has a code of conduct which you enforce.
