### ISSUE TITLE
Application not working after reinstall 

### ISSUE THREAD

**Issue by javixeneize** [nhsx/COVID-19-app-Android-BETA#21]
The application does a device registration process during startup. However, when the app is uninstalled and installed again it does no longer work, as i believe it tries to register the device again when it is already registered

**Comment by edent** [comment]
Thanks - we'll look into it. Could you please provide your phone's make, model, and Android version number?

**Comment by javixeneize** [comment]
Sure. It’s a motog Falcón using android 7, but my understanding is that it’s a problem in the back end and not related to the device

**Comment by billysielu** [comment]
I uninstalled and reinstalled on Galaxy S6 Android 7.0 and did not experience an issue.

**Comment by theterminator3000** [comment]
I uninstalled and reinstalled on a Galaxy S9+ Android 10.0 and also did not experience an issue

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
