### ISSUE TITLE
Gradle Build Failure - google services

### ISSUE THREAD

**Issue by Harp3rBoy** [nhsx/COVID-19-app-Android-BETA#23]
When trying to build the application I get the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. `

**Comment by calfr** [comment]
If you head to [Firebase](https://firebase.google.com/), head through the flow to create a project and add an android app to it (you probably want to register a different package name and change the name in build.gradle), you can then download the google-services.json file and place it at one of the paths given in the error, and it should get you past that step of the build.
I don't know if this'll complete the build or if more work might be needed later down the line, but it does get past that error.

**Comment by gilescope** [comment]
That seems to work well - save the google-services.json that it gives you to ./app/google-services.json and then in `app\build.gradle` replace `uk.nhs.nhsx.colocate` with your firebase app id that you've just created.

From there gradlew builds through to the point where it's expecting an android device to be attached.

**Comment by hithomasmorelli** [comment]
If an Android device is connected, it then runs through some tests to the point where it expects `sonar.baseUrl` to be contactable

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
