### ISSUE TITLE
Shared device access problem

### ISSUE THREAD

**Issue by adarrel753** [nhsx/COVID-19-app-Android-BETA#28]
I'm not sure if this is the right place to post this but here goes...

Use Case Scenario:

- Child breaks own phone playing football in the garden.
- Parent can't afford to replace their phone until payday so lends their own phone to their child for a few hours a day until then.
- Parent receives a message indicating they have been in close contact with someone who is now presenting Covid-19 symptoms

Q. Is it possible to determine who (parent or child) the message is intended for?

Q. Can shared access be detected?

**Comment by zymurgic** [comment]
(child, or other user of the device, could be aged over 18, before someone suggests children aren't supposed to be using this app, and dismisses this problem). Later versions of Android may support multiple users and switching of user profiles, but does this app support this distinction?

**Comment by edent** [comment]
This is a good point.  From the usage instructions https://covid19.nhs.uk/using-the-app.html

> Everyone in your house should download and use the NHS COVID-19 app on their own phone if they have one. The app is designed to be used by one person on one device.

We are aware that not everyone has / can afford a smart device.

From our FAQ https://faq.covid19.nhs.uk/article/KA-01018/en-us
> Everyone will benefit from the NHS COVID-19 App because - if enough people with smartphones do download it - it will help slow the epidemic and protect the NHS. Nevertheless, we are working with the Department of Digital, Culture, Media and Sport to mitigate the impact of digital exclusion. 

> The Government is supporting the DevicesDotNow campaign to get internet-enabled devices and support for vulnerable people isolated in their homes without internet access. Devices are being distributed through community organisations that are also providing the support needed to enable people lacking digital skills and confidence to use the devices and access the internet and online services. The campaign is prioritising people who are digitally excluded and shielding or vulnerable due to age, disability, health conditions and social isolation.

**Comment by adarrel753** [comment]
If there was a phone number the parents could call, they could voluntarily tell you their installation ID and the timeframes that they were using the phone. From their, NHS staff (or some other gov entity) could inspect the central database for the context event(s) involved and help the parents resolve the dilemma. This would have to be conducted carefully no doubt (in terms of protection privacy rights vs. granting a parent the right to take care of themselves and children) but it seems clear to me that scenario would be better handled with a centralised system. Providing assistance like this wouldn't be possible without a central database I think and the number of edge case scenarios like this that could come up in a system used by millions could be vast.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
