### ISSUE TITLE
Notification when screen turned off in Battery Saver.

### ISSUE THREAD

**Issue by thunter1000** [nhsx/COVID-19-app-Android-BETA#29]
**Describe the bug**
When phone is on battery saver mode and the screen turns off, the app notifies the user. Turning the screen on dismisses the notification (before you are able to read it). I assume it is a notification to tell me to turn on location or bluetooth.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on battery saver.
2. Turn off the screen.
3. Device notifies almost immediately.
4. Turning on the screen you can very briefly see the notification as it is dismissed.

I also believe the app is also notifying periodically with the screen off. But I cannot see the notification fast enough to confirm it.

**Expected behaviour**
The application shouldn't notify me every time I turn the phone display off. If there is an issue with tracing when in battery saver it should notify me when I turn the feature on.

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - OS: Android
 - Version: 10
 - Security Update: April 5, 2020

**Comment by edent** [comment]
I'm able to reproduce this on my OnePlus 5T with battery saver turned on. It dismisses almost instantly when the screen is turned on.

I assume this behaviour is because battery saver only disabled BLE when the screen is off. So it's hard to notify the user *before* that happens. We'll pick this up with the team and see what we can do.

Thanks for reporting this.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
