### ISSUE TITLE
Remove or make optional identifying phone information

### ISSUE THREAD

**Issue by Xenoamor** [nhsx/COVID-19-app-Android-BETA#31]
Upon registration "deviceModel" and "deviceOSVersion" are submitted.

I believe there is an argument against doing so for the purposes of privacy. I can't see why this information is needed.

If this is required for crash reports then I propose that information is instead sent upon a crash _with_ the users permission and only when necessary.

What are the arguments for this data?

**Comment by edent** [comment]
We have set out the reason for this information in the [Data Protection Impact Assessment (DPIA)](https://faq.covid19.nhs.uk/article/KA-01043/en-us).

> The make and model of the device (e.g. Apple iPhone 10) is used help interpret the data – as bluetooth signal strength varies between devices.

The basis for processing this is also set out in the [Data Dictionary](https://faq.covid19.nhs.uk/1.%20IMP%20-%20Reference%20-%20Data%20Dictionary%20(downloaded%2002052020%200831%20AM).pdf)

> Basis for Processing
> ● Estimating distance between devices from signal strength reported during BLe interactions varies by device

**Comment by Xenoamor** [comment]
Thanks for the document links, that clears up a lot of questions I had.

For discussion on whether or not BLE distance ranging is valid/accurate see #30
