### ISSUE TITLE
app sends data to Microsoft servers in US

### ISSUE THREAD

**Issue by doug-leith** [nhsx/COVID-19-app-Android-BETA#33]
I took some measurements of the network connections made by the NHS app and observe that it makes connections to a server in.appcenter.ms.  This seems to be part of the operation of the appcenter SDK used by the app.   Connections are made both on initial install of the app and also intermittently while it is left running.  

GeoIP services indicate that in.appcenter.ms is likely located in Virginia, US and RTT measurements that I've taken are consistent with this.

Will the production version of the app also use the appcenter SDK and make similar connections?  If so, does that raise privacy concerns re export of data (including meta-data) of UK citizens to the US?

**Comment by adarrel753** [comment]
The dev team can probably shed more light on what's going on there but one thing the phone will need to do is contact the app centre periodically to check if app updates are available for download.

**Comment by edent** [comment]
From [the DPIA](https://faq.covid19.nhs.uk/DPIA%20COVID-19%20App%20PILOT%20LIVE%20RELEASE%20Isle%20of%20Wight%20Version%201.0.pdf)

> Performance data
During the limited release in the Isle of Wight, additional data will be
collected about the App’s performance and user interactions with the
App. This data will be captured through the Microsoft AppCentre and
will not include the SonarID or any other identifying information, and 
will not be linked with any identifying information. This data is
collected to help us understand whether the App and the related
infrastructure is functioning as intended. This is necessarily held on
Microsoft servers away from our platform, as some of the metrics
are for the inability to contact our service.

Regarding GDPR, we require all third parties to be compliant. In this case, from later in the same document:

> Will the contract contain standard clauses to require compliance with the GDPR?
> Microsoft - Microsoft Online Services Data Protection Addendum January 2020

**Comment by doug-leith** [comment]
Could you confirm that appcenter will not be used in the production app, thanks (the DPIA doc you cite does not state this explicitly).   Closing this thread without that clarification seems inappropriate.

**Comment by edent** [comment]
The plan is only use these analytics on the Isle of Wight release.  As we say [in the blog post](https://www.nhsx.nhs.uk/blogs/code-behind-nhs-covid-19-app/):

> The public version of the app does not use any third-party analytics. In order to improve the app, we need to collect information about what happens if it crashes. This will use the operating system's default error-reporting tools.
>
> Our closed Beta will collect some volunteers' data for performance analytics and A/B testing. The libraries required for these analytics may still be present - but deactivated -  in the public version of the app.
