### ISSUE TITLE
No automated checks or release flows

### ISSUE THREAD

**Issue by hitherejoe** [nhsx/COVID-19-app-Android-BETA#35]
Hey @edent - as per the README, I noticed that tests are being run manually before pushing PRs, along with releases being handled from a local machine also.

With this being an open source app, github actions would be free to use. This would allow you to run the tests for the project when PRs are opened. You could even handle the release process of the app via github actions also. I recently wrote a blog post about how we are doing this @ Buffer [here](https://overflow.buffer.com/2020/05/07/using-github-actions-for-android-continuous-integration-and-delivery/).

With the above in place, I believe that you'd not only helping to ensure quality standards but also remove time spent on manual checks. If this is something that you think would benefit the project, I'd be more than happy to help set this up 🙂

**Comment by hitherejoe** [comment]
Ah, looks like they are already setup. Any reason why they aren't running on PRs? 🙂

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
