### ISSUE TITLE
Consider BT5 advertising extensions as an alternative to send the anonymized id

### ISSUE THREAD

**Issue by homer-jay** [nhsx/COVID-19-app-Android-BETA#36]
Have you considered [BT5 extended advertising](https://source.android.com/devices/bluetooth/ble_advertising)? It is available in Android 8 and higher.
This mechanism would eliminate the need of opening a connection to every nearby device to send them the anonymized user ID (which I understand is how it works as of now). This would potentially be more battery efficient and faster.
The Gatt server would have to be maintained as a fallback for older devices though.

**Comment by Xenoamor** [comment]
I see no reason to add it and to have two systems in place competing
Standard BLE as it is uses very little power anyway, especially with long connection intervals

**Comment by gilescope** [comment]
@homer-jay I would ber concerned that the reciever would have to be in android 8 and higher as well I would imagine? I think the lowest common denominator tech is best for maximum transmision. We want to be able to interact with old phones even if we've got a new one.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
