### ISSUE TITLE
Data saver mode

### ISSUE THREAD

**Issue by adarrel753** [nhsx/COVID-19-app-Android-BETA#37]
I presume that this app needs to be able to use mobile data in the background to support people using phones while away from Wi-Fi. If so it maybe worth asking the user to allow this while in Data Saver mode too.

![Screenshot_20200515-083806_Settings](https://user-images.githubusercontent.com/44327273/82025177-e0d51100-9688-11ea-9bd5-4d01d8e9cb18.jpg)

**Comment by Xenoamor** [comment]
If data saver mode blocks BLE use then yes it will but I don't believe it does. The app only relies on an internet connection when it is open as far as I'm aware. Primarily when registering and reporting symptoms

**Comment by adarrel753** [comment]
I think the bigger problem would be if it stopped someone from getting notifications

**Comment by Xenoamor** [comment]
Would require testing but yes that would be cause for concern. You'd hope the user would check their app at least daily though

**Comment by adarrel753** [comment]
Perhaps the app could show a basic phone notification (the type of notifications that any app can issue to a phone I mean) if it fails to connect to the central server for an extended period of time? For example: 

*The NHS COVID-19 app has been unable to connect to the central server since hh:mm on dd/mm/yyyy. Please make sure your phone can connect to the Internet

**Comment by philipswift** [comment]
The less information the App feeds back to the end-user the better.
Server-side timestamps could provide Unique Identification (meta) if
analysis of frequency and duration of connectivity is needed. Probably best
not to have this as it's bloaty. Keep it slim and KISS.

**Comment by adarrel753** [comment]
If there is a Covid-19 notification waiting to go out to the end-user, they will not be able to receive it until they sort their phone out. The 'no news is good news' approach won't help them protect their family.

**Comment by edent** [comment]
Thanks for the report. Which specific phone is that on? We are testing things like datasaver, app firewalls, etc. But, ultimately, if someone chooses to turn off data, or to go onto silent mode, there isn't much we can do.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
