### ISSUE TITLE
Track iOS device in background

### ISSUE THREAD

**Issue by gnuhel** [nhsx/COVID-19-app-Android-BETA#44]
**Describe the bug**
As far as I know, there is a limitation on iOS that it only sends limited information when the iOS device is in the background. How can the Android app track the iOS device in the background when there is no unique identifier which identifies the user?

**Comment by lukeredpath** [comment]
They are reverse engineering what iOS does and inspecting the Bluetooth advertising packet to detect and establish a connection with the iOS app. See https://github.com/nhsx/COVID-19-app-Android-BETA/issues/10

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
