### ISSUE TITLE
On most Android Bluetooth interactions need to be done with synchronization

### ISSUE THREAD

**Issue by acooley** [nhsx/COVID-19-app-Android-BETA#45]
**Describe the bug**
So, like most thread safety issues this only shows up under load, but I suspect you are seeing strange Bluetooth error message at random times particularly on some handsets like older Samsungs.

**To Reproduce**
Load up an older Samsung S7 with Bluetooth requests

**Expected behaviour**
You shouldn't get errors, but you do.

**Additional context**
I've done lots of load testing and development on Android as part of projects with HP and Cisco, and I have my own BLE open source project.  I suggest you adopt a Kotlin object and sync on it as you interact with the different Android Bluetooth APIs.

See https://github.com/kunai-consulting/OpenTrace/blob/develop/android/app/src/main/java/ai/kun/socialdistancealarm/alarm/BLETrace.kt as a reference.

**Comment by edent** [comment]
Thanks Aaron. Can you be a bit more specific about the errors you're encountering? Log files would be helpful.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
