### ISSUE TITLE
You should be using Alarm Manager to keep BLE running

### ISSUE THREAD

**Issue by acooley** [nhsx/COVID-19-app-Android-BETA#46]
**Describe the bug**
So according to the epidemiologists that we have been working with on OpenTrace you want to scan every 5 minutes.  The only way to do that on Android is to use AlarmManager and cheat by having your onRecieve method schedule another alarm.  You aren't doing that, and thus your app is subject to getting dozed by the operating system.

**To Reproduce**
Run this app long enough and it will stop scanning and broadcasting on some handsets under some manufacturer specific battery optimizations, etc.

**Expected behaviour**
There's really no reason an Android app should be limited.  Our app scans every 10 seconds, runs for days, doesn't drain the battery.

You can see a proper implementation here in our project:

https://github.com/kunai-consulting/OpenTrace/blob/develop/android/app/src/main/java/ai/kun/socialdistancealarm/alarm/BLETrace.kt

The TCN project works the same way as our does.

**Comment by edent** [comment]
Thanks Aaron. Do you have any details of handsets which exhibit this behaviour? Part of our beta trial is looking at things like battery optimisation - and it's really helpful to know which specific devices we should be testing.
I'll pass on the point about using Alarm Manager.

**Comment by craigrouse** [comment]
@edent Huawei/Honor devices very aggressively kill apps in the background (my wife has one and despite having added exceptions for many apps in the power settings, it still kills things that have been in the background for a while). Samsung is another manufacturer that has a reputation for aggressive power management, but I don't have many issues with my own Samsung device. Hope this is useful.

**Comment by microadam** [comment]
Here is a website that details how to prevent specific devices from specific vendors from killing your app: https://dontkillmyapp.com/

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
