### ISSUE TITLE
Secondary app for use by law-enforcement, at infection hot-spots or near sensitive infrastructure

### ISSUE THREAD

**Issue by carpetrex** [nhsx/COVID-19-app-Android-BETA#47]
**Idea:** To take best advantage of the centralised model, there should be a secondary app (running on any appropriate OS/hardware), available only to law-enforcement or for special use in specific areas.

The secondary app should function broadly similarly to the primary app, initiating BLE contacts with the primary app and reporting its contacts as usual to the primary server. However, this app should also:

- Report its identifiers and location back to a secondary server. When the app is installed alongside an existing piece of infrastructure (such as ANPR/Facial recognition cameras, contactless payment terminals, transport hubs etc), identifiers for this infrastructure should also be passed to the secondary server.

- Transmit more often and at maximum power to allow the greatest number of BLE contacts to be created - without regard to battery usage, on an OS/hardware platform which allows for this.

Very valuable additional information could be gathered and inferred if sufficient instances of the secondary app can be ran, spread across the country. Using administrator access to the data on the primary server (including BLE contacts between primary app users, and the secrets shared by the primary app during signup), this secondary app and secondary server will allow for:

- Visitors to infection hot-spots to be highlighted in datasets, regardless of whether their primary app shares a BLE contact with someone who subsequently reports themselves as infected.
- Real-name identities, locations and demographic information to be added to the infection-control dataset by cross-referencing data between the primary server, the secondary server and datasets for existing surveillance platforms (such as ANPR/Facial rec cameras etc which have the secondary app nearby). This additional information could increase the usefulness of the primary app to health authorities.
- Undesirable persons to be tracked more easily, and their contacts with others to be easily determined. This will allow for improvements to our society beyond simply reducing virus infections.

The secondary app/server need not be known to the developers of the primary app, and should be developed separately.

**Comment by edent** [comment]
As this doesn't relate to technical issues with the current version of the app, I'm closing this issue.

**Comment by carpetrex** [comment]
I was genuinely hoping that there would be clear features in the current app which made the secondary app that I propose impossible. 

I understand you have nowhere near enough time to discuss a hypothetical other project though. Thank you for engaging with people on here.
