### ISSUE TITLE
Validate interaction with medical devices (CGM, pacemakers, etc.)

### ISSUE THREAD

**Issue by micolous** [nhsx/COVID-19-app-Android-BETA#50]
**Describe the bug**

Multiple folks have reported issues with Australia's TraceTogether based app (COVIDSafe) interfering with apps that interface with continuous blood-glucose monitors (CGM) used to manage diabetes:

* https://twitter.com/DiabetesAus/status/1255671094800871426
* https://twitter.com/jim_mussared/status/1256501782148075520

NHSx's app also uses GATT, and switches the device between peripheral and central modes, so is likely to trigger the same issue.

This may vary based on device model, as not all Bluetooth controllers can run in both Bluetooth Classic and LE modes simultaneously.

While this is likely to be a bug in some medical device software, contact tracing software operating in GATT mode triggers this issue through its constant manipulation of the Bluetooth controller in the background.

NHSx should validate this behaviour before public release.

**To Reproduce**

1. Pair/bond a CGM to a phone via Bluetooth and install its app
2. Install NHSx COVID-19 app
3. Verify that the CGM app is operating correctly (eg: alerting on changes to blood-glucose levels in the background)
4. Repeat the test for multiple models of CGM
5. Repeat the test for multiple phone models
6. Repeat the test for other bluetooth medical devices (eg: pacemakers)

**Comment by edent** [comment]
Thanks Michael. We're testing this with people who use a range of Bluetooth devices - some medical, some not.

Do you have any specific models that you know exhibit this behaviour?

I can't comment about the Australian app.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
