### ISSUE TITLE
Is the app okay for phones enrolled in Android Enterprise management?

### ISSUE THREAD

**Issue by markalanrichards** [nhsx/COVID-19-app-Android-BETA#51]
**Describe the bug**
Many people in the UK get mobile phones from their work place.
Employees with company provided android phones may have their device setup with Android Enterprise features enabled that may include global proxies, vpns, custom root certificates installed and enhanced monitoring of applications and activity of the device.

This list might help understand some of the features: https://developers.google.com/android/work/requirements

Which raises a few issues:
- Should employers forbid this application on corporate devices?
- Should employers distribute this application on corporate devices (user's may not have install privileges)?
- How does this affect the privacy promises of the application to users?
- Are there any code changes that the application can take to protect privacy on these company provided devices?

**Expected behaviour**
Users and employers are at least provided guidance on this topic and understand the risks (if any).
Given the privacy goals of the application, efforts should be made to minimise the privacy risks here; although to what extent that is possible may depend on how intrusive the Android Enterprise features are at intercepting network traffic, recording application behaviour and accessing device storage.

**Comment by edent** [comment]
Hi Mark, I don't think we've yet issued guidance on corporate devices.  It is up to the corporate owner if they want to prevent this (or any other) app from being installed.

I'll see if we have plans to make such guidance available.

From my understanding of the Android Enterprise / Work Profile, an admin wouldn't be able to see the data generated by the app and stored on the handset. But if you have any specific mitigations in mind, please let us know.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX

**Comment by akuckartz** [comment]
How was this issue resolved?

**Comment by hithomasmorelli** [comment]
This particular project has ended - this app is no longer in use

**Comment by akuckartz** [comment]
In that case this repository should have been archived instead of closing all the unresolved issues.
